### ISSUE TITLE
Is your code working?

### ISSUE THREAD

**Issue by lvu213120315** [yunginnanet/mullsox#2] opened 2024-07-05 00:21 UTC
// init Mullvad checker
	checker := mullvad.NewChecker()
	log.Println("Mullvad checker initialized")

	// init proxy engine
	proxyEngine := prox5.NewProxyEngine()
	log.Println("Proxy engine initialized")

	// get and verrify SOCKS servers
	verifiedServers, errChan := mullsox.GetAndVerifySOCKS(checker)
	if verifiedServers == nil {
		log.Fatal("No verified servers channel returned")
	}
	if errChan == nil {
		log.Fatal("Error channel is nil")
	}

	log.Println("Channels initialized, starting to process servers...")

	// count of proxies loaded
	proxyCount := 0
	timeout := time.After(2 * time.Minute)
	

i'm stuck at // get and verify SOCKS servers
Is your code working?

**Comment by yunginnanet** [comment] 2024-07-05 00:27
looks like the example on the readme needs to be updated to reflect breaking changes in the API 

but, yes, generally speaking [it works](https://github.com/yunginnanet/mullsox/actions/runs/9542036875/job/26296164993).

if you need examples of usage in the mean time check the [unit tests](https://github.com/yunginnanet/mullsox/blob/main/sox_test.go)

**Comment by yunginnanet** [comment] 2024-07-05 00:46
I updated the checker's concurrency mechanism, confirmed this snippet works:

```go
package main

import (
	"git.tcp.direct/kayos/mullsox"
	"git.tcp.direct/kayos/mullsox/mullvad"
)

func main() {
	fetcher := mullvad.NewChecker()
	socksCh, errCh := mullsox.GetAndVerifySOCKS(fetcher)
	go func() {
		for err := range errCh {
			println(err.Error())
		}
	}()
	for sock := range socksCh {
		println(sock.String())
	}
}
```

though it appears their (Mullvad's) SOCKS relays are timing out from what I can see on my end

**Comment by yunginnanet** [comment] 2024-07-06 15:47
Please let me know if this answers your question, if I don't hear back I'll be closing this issue.

**Closed** 2024-07-06 19:19 UTC
